[project]
name = "projeto-igreja"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiosqlite>=0.21.0",
    "fastapi>=0.116.1",
    "jinja2>=3.1.6",
    "sqlalchemy>=2.0.43",
    "uvicorn>=0.35.0",
]
